name: Build

on: push

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install g++ (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install g++
      - name: Build code (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: g++ hello.cpp -o hello
      - name: Build code (Windows)
        if: startsWith(matrix.os, 'windows')
        run: g++ hello.cpp -o hello.exe
      - name: Save artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
         name: hello
         path: | hello
