name: Build

on: push

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install g++ (Linux)
        run: sudo apt-get install g++

      - name: Build code (Linux)
        run: g++ hello.cpp -o hello

      - name: Run executable (Linux)
        run: ./hello

      - name: Save artifact (Linux)
        if: always()
        uses: actions/upload-artifact@v2.2.4
        with:
         name: hello
         path: ./hello

